In this notebook, we will find the optimal learing rate for the pooled RCNN model.

# 1. Loading Data

In [1]:
from IPython.display import clear_output

def hint(message):
    """
    erase previous ipynb output and show new message
    """
    clear_output()
    print(message)

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

hint("loading data...")
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

labels = [
    'toxic', 
    'severe_toxic', 
    'obscene', 
    'threat', 
    'insult', 
    'identity_hate'
]

Y = train[labels].values

hint("Done")

Done


# 2. Pre-processing

## 2.1 Cleaning

Gather resources

In [3]:
from nltk.stem.wordnet import WordNetLemmatizer
import nltk

nltk.download('wordnet')

lmtzr = WordNetLemmatizer()
eng_stopwords = (
    'what', 'which', 'who', 'whom', 
    'this', 'that', 'these', 'those', 
    'am', 'is', 'are', 'was', 'were', 
    'be', 'been', 'being', 
    'have', 'has', 'had', 'having', 
    'do', 'does', 'did', 'doing', 
    'a', 'an', 'the', 
    'and', 'but', 'if', 'or', 
    'because', 'as', 'until', 'while', 
    'of', 'at', 'by', 'for', 'with', 
    'about', 'against', 'between', 
    'into', 'through', 'during', 'before', 'after', 
    'above', 'below', 'to', 'from', 
    'up', 'down', 'in', 'out', 'on', 'off', 
    'over', 'under', 'again', 'further', 
    'then', 'once', 'here', 
    'there', 'when', 'where', 'why', 
    'how', 'all', 'any', 'both', 'each', 
    'few', 'more', 'most', 'other', 'some', 
    'such', 'no', 'nor', 'not', 'only', 
    'own', 'same', 'so', 'than', 'too', 'very', 
    'can', 'will', 'just', 'don', 'should', 'now'
)
appos = {
    "aren't" : "are not",
    "can't" : "cannot",
    "couldn't" : "could not",
    "didn't" : "did not",
    "doesn't" : "does not",
    "don't" : "do not",
    "hadn't" : "had not",
    "hasn't" : "has not",
    "haven't" : "have not",
    "he'd" : "he would",
    "he'll" : "he will",
    "he's" : "he is",
    "i'd" : "I would",
    "i'd" : "I had",
    "i'll" : "I will",
    "i'm" : "I am",
    "isn't" : "is not",
    "it's" : "it is",
    "it'll":"it will",
    "i've" : "I have",
    "let's" : "let us",
    "mightn't" : "might not",
    "mustn't" : "must not",
    "shan't" : "shall not",
    "she'd" : "she would",
    "she'll" : "she will",
    "she's" : "she is",
    "shouldn't" : "should not",
    "that's" : "that is",
    "there's" : "there is",
    "they'd" : "they would",
    "they'll" : "they will",
    "they're" : "they are",
    "they've" : "they have",
    "we'd" : "we would",
    "we're" : "we are",
    "weren't" : "were not",
    "we've" : "we have",
    "what'll" : "what will",
    "what're" : "what are",
    "what's" : "what is",
    "what've" : "what have",
    "where's" : "where is",
    "who'd" : "who would",
    "who'll" : "who will",
    "who're" : "who are",
    "who's" : "who is",
    "who've" : "who have",
    "won't" : "will not",
    "wouldn't" : "would not",
    "you'd" : "you would",
    "you'll" : "you will",
    "you're" : "you are",
    "you've" : "you have",
    "'re": " are",
    "wasn't": "was not",
    "we'll":" will",
    "didn't": "did not"
}

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ChuanLi\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


Define cleaning method

In [4]:
from nltk.tokenize import TweetTokenizer
import re

tkzr = TweetTokenizer(preserve_case=False)

def preprocess(comment):
  
    # credit to the author of this post:
    # https://www.kaggle.com/jagangupta/stop-the-s-toxic-comments-eda

    # remove special format
    comment = re.sub('\n\t', '', comment)

    # remove IP addresses
    comment = re.sub('\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}', ' specipaddress ', comment)

    # remove username
    comment = re.sub("\[\[User.*\]", ' specusername ', comment)
    comment = re.sub("\[\[User.*\|", ' specusername ', comment)

    # tokenization 
    tokens = tkzr.tokenize(comment)

    # aphostophe replacement
    tokens = [ appos[token] if token in appos else token for token in tokens]

    # remove stopwords
    tokens = [ token for token in tokens if not token in eng_stopwords ]

    # stemming
    tokens = [ lmtzr.lemmatize(token, 'v') for token in tokens]

    return " ".join(tokens)

Cleaning

In [5]:
hint("Cleaning train set...")
X = train['comment_text'].apply(lambda c: preprocess(c))
hint("Cleaning test set...")
X_ = test['comment_text'].apply(lambda c: preprocess(c))
hint("Done")

Done


## 2.2 Making Sequences

In [7]:
from keras.preprocessing import text as ktxt, sequence

vocab_max = 100000

hint("Fitting the tokenizer...")
tokenizer = ktxt.Tokenizer(num_words=vocab_max)
tokenizer.fit_on_texts(X)

hint("Tokenizing...")
X = tokenizer.texts_to_sequences(X)
X_ = tokenizer.texts_to_sequences(X_)

hint("Padding the sequences...")
max_comment_length = 200  # padded/cropped comment length
X = sequence.pad_sequences(X, maxlen=max_comment_length)
X_ = sequence.pad_sequences(X_, maxlen=max_comment_length)

hint("Done")

Done


## 2.3 Prepare Embedding Matrix

In [8]:
import csv

emb_file = 'preembedding/glove.840B.300d.txt'

hint("Loading pre-embedding file...")
emb = pd.read_table(emb_file, " ", index_col=0, header=None, quoting=csv.QUOTE_NONE)

hint("Preparing embedding matrix...")
embedding_dimension = 300
embedding_matrix = np.random.normal(
    emb.mean(axis=0), 
    emb.std(axis=0), 
    (vocab_max, embedding_dimension)
)

hint("Done")

Done


In [9]:
hint("Constructing embedding matrix")
for word, i in tokenizer.word_index.items():
    if i < vocab_max and word in emb.index:
        embedding_matrix[i] = emb.loc[word].as_matrix()

hint("Done")

Done


In [10]:
del emb

# 3. Model and Training

## 3.1 Model Definition

In [13]:
from keras.models import Sequential, Model
from keras.layers import Input, Dense, Embedding, CuDNNGRU, CuDNNLSTM, BatchNormalization
from keras.layers import SpatialDropout1D, Dropout, TimeDistributed, Bidirectional
from keras.layers import GlobalMaxPooling1D, GlobalAveragePooling1D, concatenate
from keras.layers.convolutional import Conv1D, MaxPooling1D
from keras.optimizers import Adam
from attention_decoder import AttentionDecoder

def get_model(input_dim, embedding_matrix, lr):
    sequence_input = Input(shape=(input_dim, ))
    x = Embedding(vocab_max, embedding_dimension, weights=[embedding_matrix])(sequence_input)
    x = SpatialDropout1D(0.5)(x)
    x = Conv1D(filters=256, kernel_size=3, padding='same', activation='relu')(x)
    x = MaxPooling1D(pool_size=2)(x)
    x = SpatialDropout1D(0.2)(x)
    x = Bidirectional(CuDNNGRU(64, return_sequences=True))(x)
    avg_pool = GlobalAveragePooling1D()(x)
    max_pool = GlobalMaxPooling1D()(x)
    x = concatenate([avg_pool, max_pool])
    x = Dropout(0.2)(x)
    preds = Dense(1, activation="sigmoid")(x)
    model = Model(sequence_input, preds)
    model.compile(
        loss='binary_crossentropy',
        optimizer=Adam(lr=lr), 
        metrics=['accuracy']
    )
    return model

models = [ get_model(max_comment_length, embedding_matrix, 0.0003) for _ in range(6) ]
print("Models ready")

Models ready


In [14]:
from sklearn.utils import class_weight

class_weights = []
for i in range(6):
    class_weights.append(class_weight.compute_class_weight(
        'balanced', 
        np.unique(Y[:, i]), 
        Y[:, i]
    ))
print("Class weight matrix: ")
class_weights

Class weight matrix: 


[array([0.55300221, 5.21678436]),
 array([ 0.50504824, 50.02225705]),
 array([0.52795424, 9.44318854]),
 array([  0.50150227, 166.91527197]),
 array([ 0.52596345, 10.12891964]),
 array([ 0.50444154, 56.78683274])]

## 3.2 Training

In [ ]:
from keras.callbacks import EarlyStopping

epochs = 10
batch_size = 64
val_loss_estop = EarlyStopping(monitor='val_loss')
loss_estop = EarlyStopping(monitor='loss', min_delta=0.0001, patience=1)
callback_list = [loss_estop, val_loss_estop]

history = []
for i, label in enumerate(labels):
    print('Fitting class \"%s\"' % label)
    history.append(models[i].fit(
        X, Y[:, i], 
        epochs=epochs, 
        batch_size=batch_size,
        callbacks=callback_list,
        class_weight=class_weights[i]
    ))
    print(' ')

Fitting class "toxic"
Epoch 1/10
159571/159571 [==============================] - 72s 451us/step - loss: 0.1207 - acc: 0.9558
Epoch 2/10
   448/159571 [..............................] - ETA: 1:09 - loss: 0.0867 - acc: 0.9688

c:\users\chuanli\appdata\local\programs\python\python35\lib\site-packages\keras\callbacks.py:526: RuntimeWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,acc
  (self.monitor, ','.join(list(logs.keys()))), RuntimeWarning


105728/159571 [==================>...........] - ETA: 23s - loss: 0.0932 - acc: 0.9646

# 4. Submission

In [ ]:
Y_ = np.zeros((Y.shape[0], len(labels)))
for i, model in enumerate(models):
    Y_[:, i] = model.predict(X_)[:, 0]

In [ ]:
import time

hint("Uploading...")
file_name = 'submission_' + time.strftime("%Y%m%d-%H%M%S") + '.csv'
sumbit_id = pd.DataFrame({'id': test['id']})
sumbit_labels = pd.DataFrame(Y_, columns=labels)
submission = pd.concat([sumbit_id, sumbit_labels], axis=1)
submission.to_csv(file_name, index=False)
hint("Done")